FROM thrift-hindsight:latest

COPY ./ /echohindsight-tthreaded
WORKDIR /echohindsight-tthreaded
RUN cp echotthreaded.conf /etc/hindsight_conf; \
    cp echottdhs_supervisor.conf /etc/echottdhs_supervisor.conf; \
    make server.o && cp server.o /etc/server.o

EXPOSE 5050
EXPOSE 3046

CMD [ "supervisord", "-c", "/etc/echottdhs_supervisor.conf" ]


# docker run --rm -it  -p 3046:3046/tcp -p 5252:5252/tcp --shm-size 8G echottdhs:latest